version: '3.7'

services:
  idempiere:
    image: idempiereofficial/idempiere:8.2
    ports:
      - 8181:8080
      - 40612:12612
    environment:
      - TZ=America/Guayaquil
    networks:
      - idempiere_demo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:12
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_PASSWORD=postgres
    networks:
      - idempiere_demo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  idempiere_demo:
    external: true
