version: '3.7'

services:
  idempiere:
    image: idempiereofficial/idempiere:daily
    ports:
      - 8091:8080
      - 8612:12612
    environment:
      - TZ=America/Guayaquil
    networks:
      - idempiere_demo_official
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:13
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_PASSWORD=postgres
    networks:
      - idempiere_demo_official
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  idempiere_demo_official:
    external: true
