version: '3.7'

services:
  idempiere:
    image: idempiereofficial/idempiere:8.2
    ports:
      - 8092:8080
      - 8613:12612
    environment:
      - TZ=America/Guayaquil
      - MIGRATE_EXISTING_DATABASE=true
    networks:
      - idempiere_demo_official_release
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:13
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_PASSWORD=postgres
    networks:
      - idempiere_demo_official_release
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  idempiere_demo_official_release:
    external: true
