pipeline {
    agent none
    environment {
        IDEMPIERE_REPOSITORY = "/idempiere"

    }
    stages {
        stage('Build Artefact') {
            agent {
                docker {
                    image 'portus.ingeint.com/idempiere-source:8.2'
                    registryUrl 'https://portus.ingeint.com'
                    registryCredentialsId 'portus-ingeint'                 
                }
            }
            steps {

                sh 'docker run -d --name source idempiere:source-release-8.2 sleep 200'
                sh 'docker cp source:/source/idempiere/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64 ./idempiere'

                sh 'ls /idempiere'
                
                archiveArtifacts artifacts: '/idempiere', fingerprint: true
                stash includes: '/idempiere', name: 'workspace'
            }
        }
    }
}
