pipeline {
    agent none
    environment {
        IDEMPIERE_REPOSITORY = "/idempiere"

    }
    stages {
        stage('Build Artefact') {
            agent {
                docker { image 'docker:19' }
            }
            steps {
                sh 'docker run -d --name source-release idempiere:source-release-8.2 sleep 60'
                sh 'docker cp source:/source/idempiere/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64 ./idempiere'
            }
        }
    }
}
