pipeline {
    agent none
    environment {
        IDEMPIERE_REPOSITORY = "/idempiere"
        REGISTRY_PASS = credentials('ingeint-registry-pass')

    }
    stages {
        stage('Build Artefact') {
            agent {
                docker { 
                     image 'docker:19'
                }
            }
            steps {
                sh 'docker login $REGISTRY_REPOSITORY -u $REGISTRY_USER -p $REGISTRY_PASS'
                sh 'docker run -d --name source portus.ingeint.com/idempiere-source sleep 60'
                sh 'docker cp source:/idempiere/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64 ./source-idempiere '
                sh 'ls'

                archiveArtifacts artifacts: '/source-idempiere', fingerprint: true
                
                sh 'docker rm -f source '
            }
        }
    }
}
